# Generated by Django 4.1.4 on 2022-12-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=200)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.RenameField(
            model_name="account",
            old_name="client",
            new_name="account_number",
        ),
        migrations.AlterField(
            model_name="account",
            name="tansaction_key",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposit_account",
                to="api.account",
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdraw_account",
                to="api.account",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="api.customer",
            ),
        ),
    ]
