# Generated by Django 4.1.4 on 2022-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customer_rename_client_account_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
