# Generated by Django 4.1.4 on 2023-01-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="flag",
            field=models.BooleanField(default=False),
        ),
    ]
