# Generated by Django 4.1.4 on 2023-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_account_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
