# Generated by Django 4.1.4 on 2023-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_deposit_id_alter_transfer_id_alter_withdraw_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="id",
            field=models.CharField(
                editable=False, max_length=32, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="id",
            field=models.CharField(
                editable=False, max_length=32, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="id",
            field=models.CharField(
                editable=False, max_length=32, primary_key=True, serialize=False
            ),
        ),
    ]
