# Generated by Django 4.1.4 on 2023-01-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_deposit_id_alter_transfer_id_alter_withdraw_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
