# Generated by Django 4.1.4 on 2023-01-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_appussers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APPUssers",
        ),
    ]
