# Generated by Django 4.1.4 on 2023-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_apptoken_appuser_delete_appusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apptoken",
            name="dateTime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
