# Generated by Django 4.1.4 on 2023-01-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_apptoken_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_account",
                to="api.account",
                unique=True,
            ),
        ),
    ]
