# Generated by Django 4.1.4 on 2023-01-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_appuser_account"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AppToken",
            new_name="AppOTP",
        ),
    ]
