# Generated by Django 4.1.4 on 2023-01-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_apptoken_appotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appotp",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_account",
                to="api.account",
            ),
        ),
    ]
