# Generated by Django 4.1.4 on 2023-01-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_appotp_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUserToken",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dateTime", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_account",
                        to="api.account",
                    ),
                ),
            ],
        ),
    ]
