# Generated by Django 4.1.4 on 2023-01-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_appusertoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_account",
                to="api.account",
            ),
        ),
        migrations.AlterField(
            model_name="appusertoken",
            name="id",
            field=models.CharField(
                editable=False, max_length=32, primary_key=True, serialize=False
            ),
        ),
    ]
