# Generated by Django 4.1.4 on 2023-02-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_appuser_account_alter_appusertoken_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="account",
            field=models.ForeignKey(
                help_text="The account associated with this deposit transaction.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposit_account",
                to="api.account",
                verbose_name="Account",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="credit",
            field=models.ForeignKey(
                help_text="The account the transfer will be credited to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_account",
                to="api.account",
                verbose_name="Credit Account",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="debit",
            field=models.ForeignKey(
                help_text="The account the transfer will be debited from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debit_account",
                to="api.account",
                verbose_name="Debit Account",
            ),
        ),
        migrations.CreateModel(
            name="POS_Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=255)),
                ("phoneNumber", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("workAddress", models.CharField(max_length=255)),
                ("bankName", models.CharField(max_length=255)),
                ("nin", models.CharField(max_length=255)),
                ("bvn", models.CharField(max_length=255)),
                ("refereeFullName", models.CharField(max_length=255)),
                ("refereeAddress", models.CharField(max_length=255)),
                ("refereeNIN", models.CharField(max_length=255)),
                ("refereeBVN", models.CharField(max_length=255)),
                ("refereeAccountNumber", models.CharField(max_length=255)),
                ("refereeBankName", models.CharField(max_length=255)),
                (
                    "profilePicture",
                    models.ImageField(
                        blank=True, null=True, upload_to="pos_profile_pictures/"
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                (
                    "accountNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_account",
                        to="api.account",
                    ),
                ),
            ],
        ),
    ]
